export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_TO_CART";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const UPDATE_PRODUCT_CART = "UPDATE_PRODUCT_CART";
export const ADD_TOKEN = "ADD_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";
export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";
export const REMOVE_PRODUCTS_FROM_CART = "REMOVE_PRODUCTS_FROM_CART";